CREATE TABLE `TB_USER` (
    `SID` INT UNSIGNED AUTO_INCREMENT,
    `EMAIL` VARCHAR(50) NOT NULL,
    `USERNAME` VARCHAR(50) NOT NULL,
    `PASSWORD` VARCHAR(50) NOT NULL,
    `SEX` VARCHAR(3) NOT NULL,
    `BIRTHDAY` DATE NOT NULL,
    `AGE` INT(11) NOT NULL,
    PRIMARY KEY (`SID`) 
)