CREATE TABLE `TB_VIDEO` (
    `ID` INT UNSIGNED AUTO_INCREMENT,
    `EMAIL` VARCHAR(50) NOT NULL,
    `TYPE` VARCHAR(1024) NOT NULL,
    `SIZE` VARCHAR(50) NOT NULL,
    `PATH` VARCHAR(1024) NOT NULL,
    `TITLE` VARCHAR(1024) NOT NULL,
    `UPLOADTIME` Timestamp NOT NULL,
    PRIMARY KEY (`ID`) 
)