/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_demo_jni_Test */

#ifndef _Included_com_example_demo_jni_Test
#define _Included_com_example_demo_jni_Test
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_demo_jni_Test
 * Method:    dem
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_demo_jni_Test_dem
  (JNIEnv *, jclass);

/*
 * Class:     com_example_demo_jni_Test
 * Method:    AES_ENC
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_demo_jni_Test_AES_1ENC
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_example_demo_jni_Test
 * Method:    AES_DEC
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_demo_jni_Test_AES_1DEC
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
